### PR TITLE
Fixed leaking classes in autoloader

### LINKED ISSUE #1165: Conflict with Official WooCommerce Xero plugin
Hi,

When we are using both plugins
- WooCommerce Xero Integration - Version 1.7.37
- Image and video gallery from Google Drive - Version 2.11.1

We get the following error:
> An error of type E_COMPILE_ERROR was caused in line 13 of the file /home/xxxxxxxx/public_html/wp-content/plugins/skaut-google-drive-gallery/bundled/vendor/guzzlehttp/guzzle/src/ClientInterface.php. Error message: Cannot declare interface Sgdg\Vendor\GuzzleHttp\ClientInterface, because the name is already in use

If we disable the plugin 'Image and video gallery from Google Drive' then Zero works correctly

### LINKED ISSUE #1992: Guzzle conflicts
This has been raised to follow on from https://wordpress.org/support/topic/guzzle-coflicts/.

In the [documentation for PHPScoper (https://github.com/humbug/php-scoper/blob/main/docs/limitations.md#composer-autoloader) it says: “PHP-Scoper does not support prefixing the dumped Composer autoloader and autoloading files.

If you look at the contents of, say, autoload_classmap.php delivered with the plugin you will see that this still has the original un-namespaced class names. Whilst this may not affect the operation of this plugin, another plugin trying to load a guzzle class will find find this plugin's autoloader loading this plugin's (namespaced) version instead.

### LINKED ISSUE #1999: Konflikt s WPvidid Pluginem
Když je zapnutý plugin WPvidid a Galerie zároveň, je problém se zálohováním na Cloud.
Problém je s odesláním na Google Drive. Záloha se neodešle a zůstane uložená na FTP a to dělá problémy. Protože to jsou zálohy a na mnoha hostingách jsou takové soubory zakázané, mít je uložené na FTP s webem.

### LINKED ISSUE #2524: Autoloader classmap never being matched
The autoloader classmap is intended to make locating the file for a given class very quick (e.g. just an array lookup). However, because all the classes have been prefixed with "Sgdg\Vendor\" the array lookup ALWAYS fails and the loader resorts to searching the directories for a match - which is clearly slower.

I think a way around this is to do either of the following after composer has run:
1. edit all the lines in autoload_classmap to prefix the class names wth "Sgdg\\Vendor\\", or
2. modify the ClasssLoader->findFile to adapt the class name, e.g.: Replace:
        if (isset($this->classMap[$class])) {
            return $this->classMap[$class];
        }
By something like:
        if ( ( 'Sgdg\\Vendor\\' === substr( $class, 0, 12 ) ) && isset( $this->classMap[ substr( $class, 12 ) ] ) ) {
            return $this->classMap[ substr( $class, 12 ) ];
        }
Or something similar. For instance, modify ClassLoader::loadClass to wrap the findFile call:
public function loadClass($class)
    {
        if ( 'Sgdg\\Vendor\\' === substr( $class, 0, 12 ) ) {
            if ($file = $this->findFile( substr( $class, 12 ) ] ) ) {
                $includeFile = self::$includeFile;
                $includeFile($file);
                return \true;
            }
        }
        return null;
    }
 
I would also recommend making the classmap authoritative. Given autoloaders (i.e. yours and those used in other plugins) can be called in any order, you want to avoid your autoloader directory searching for a class that another plugin wants and either:
- Not finding it...but wasting resources doing so
- Loading one of your files that has the same name as one used in another plugin...wasting resources and maybe contributing to plugin clash

### PR DESCRIPTION
**Pull request by marekdedic**
Should close #1992 and possibly closes #1999 - @PeterSmith8nss and @kalich5, could you please check?
Closes #2524 , closes #1165

### CODE REVIEW

**Comment by PeterSmith8nss** [comment]
I've done a quick test using the build artefact from "[[Fixed leaking classes in autoloader #3654]](https://github.com/skaut/skaut-google-drive-gallery/actions/runs/5110496045)". I still seem to be getting problems when my plugin and yours are both active. One case was when your code was looking for choose_handler(). I think we are getting a clash over which version of '/guzzlehttp/guzzle/src/functions.php' is loaded - because the identifier is determined from filename, not classname.

If I comment out the two guzzle files in arrays in my autoload_static.php and autoload_files,php it seems to work. It may be that the paths I've tested in my code are not using those functions and by commenting them out your code can link the file you want to those identifiers.

Would you avoid the problem if you renamed the guzzlehttp directory, e.g. sgdgguzzlehttp before building? You need some way to avoid your file having the same file_identifier as someone else using a different version/namespace.

**Comment by PeterSmith8nss** [comment]
Just checking are these fixes in 2.13.10 or is there another zip file I
should use to get a build with this in?

**Comment by marekdedic** [comment]
@PeterSmith8nss They aren't in 2.13.10 - use this zip please (may have to rename to `skaut-google-drive-gallery.zip`): https://github.com/skaut/skaut-google-drive-gallery/actions/runs/8878119044/artifacts/1456462989

**Comment by PeterSmith8nss** [comment]
On my development system, I've deleted the existing plugin (to remove my
temporary patches) and installed from your zip file. All seems to be
working fine from the user point of view, but I'm seeing the following PHP
errors in the log:

2024-04-30 14:05:59 [php:error] PHP Fatal error:  Allowed memory size of
134217728 bytes exhausted (tried to allocate 98582528 bytes) in
/var/www/html/wp-content/plugins/build-artifact/frontend/class-video-proxy.php
on line 91, referer:
http://localhost:8080/photo-gallery/?sgdg-path-xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxOm

Not sure whether this is just a problem with the size of my development
environment/the size of my gallery or something else.

Thanks for all the work on fixing the plugin. Please let me know what
release these patches are destined for as I'm holding at my patched version
until then.

Peter

**Comment by marekdedic** [comment]
TODO: The `scoper-autoload.php` file references unprefixed globals and is included here:

https://github.com/skaut/skaut-google-drive-gallery/blob/5b415c7a84b798a584246e9be2b375c6a5b83171/src/php/skaut-google-drive-gallery.php#L52

**Comment by marekdedic** [comment]
@PeterSmith8nss Version 2.13.11 is out with the fix ;)

**Pull request merged**
